# Basic config
baseURL = "https://bytenap.netlify.app"
theme = "paper"
copyright = "Adwait Rao"
defaultContentLanguage = "en"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Setup syntax highlighting without inline styles. For more information about
# why you'd want to avoid inline styles, see
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src#unsafe_inline_styles
[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    # This allows Bear Cub to use a variation of Dracula that is more accessible
    # to people with poor eyesight. For more information about color contrast
    # and accessibility, see https://web.dev/color-and-contrast-accessibility/
    noClasses = false

# Multilingual mode config. More for information about how to setup translation,
# see https://gohugo.io/content-management/multilingual/
[languages]
  [languages.en]
    title = "ByteNap"
    languageName = "en-US 🇺🇸"
    LanguageCode = "en-US"
    contentDir = "content"

    [menu]

      [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"

      [[menu.main]]
          identifier = "posts"
          name = "Posts"
          url = "/posts"

      [[menu.main]]
          identifier = "projects"
          name = "Projects"
          url = "/projects"

    [languages.en.params]
      madeWith = "Hugo"

[params]
  # color style
  color = 'wheat'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'adwaitwt'               # twitter.com/YOUR_TWITTER_ID
  github = 'adwait-rao'                 # github.com/YOUR_GITHUB_ID
  # linkedin = 'YOUR_LINKEDIN_ID'             # linkedin.com/in/YOUR_LINKEDIN_ID
  bluesky = 'adwaitrao.bsky.social'               # https://bsky.app/profile/YOUR_BLUESKY_ID
  # rss = true                                # show rss icon

  # home page profile
  avatar = 'https://raw.githubusercontent.com/adwait-rao/bytenap/refs/heads/main/assets/adwait-img.jpeg'                 # gravatar email or image url
  name = 'Adwait Rao'
  bio = 'Building Performant backend systems with golang and Typescript'


  # misc
  disableHLJS = false                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon

  # RTL supprot
  # direction = "rtl"                         # RTL support for Right-to-left languages

#   # giscus
# [params.giscus]
#   repo = 'YOUR_GISCUS_REPO'                 # see https://giscus.app for more details
#   repoId = 'YOUR_GISCUS_REPO_ID'
#   category = 'YOUR__GISCUS_CATEGORY'
#   categoryId = 'YOUR_GISCUS_CATEGORY_ID'
#   mapping = 'pathname'
#   theme = 'light'
#   lang = 'zh-CN'
